### ISSUE TITLE
Adding random user agent may work for production mode

### ISSUE THREAD

**Issue by Maru-Yasa** [dhanuprys/brainly-api#24]
**Is your feature request related to a problem? Please describe.**
when i was deploy my app in server got 403 code response, it mean Forbidden

**Describe the solution you'd like**
maybe add a random user agent may work in production / deploy to server

**Additional context**
got error from heroku logs
![Screenshot from 2021-03-28 11-10-43](https://user-images.githubusercontent.com/41475719/112742173-48046700-8fb6-11eb-8ee7-a4d340304d5d.png)

**Comment by dhanuprys** [comment]
wassap bro, ini udah mau di develop lagi 😉

**Comment by dhanuprys** [comment]
Ini versi yang sudah di revisi..
Silahkan di coba ✋ 
[https://github.com/dhanuprys/brainly-api/releases/tag/v0.0.39-beta-fix-bug](https://github.com/dhanuprys/brainly-api/releases/tag/v0.0.39-beta-fix-bug)
